---
title: "DataVisualization ggplot2"
author: "Saikat Chowdhury"
date: "March 25, 2018"
output: html_document
---

```{r}

library(ggplot2)
```

```{r}
library(data.table)
```

```{r}
##Use fread to load the csv file 'Economist_Assignment_Data.csv' into a dataframe called df. (Hint: use drop=1 to skip the first column) Check the head rows.

df <- fread('Economist_Assignment_Data.csv',drop=1)
```
```{r}
head(df)
```
```{r}
##Use ggplot() + geom_point() to create a scatter plot object called pl. You will need to specify x=CPI and y=HDI and color=Region as aesthetics    (Graph Name--Scatterplot)
pl <- ggplot(df,aes(x=CPI,y=HDI,color=Region)) + geom_point()
```

```{r}
pl
```
```{r}
##Change the points to be larger empty circles. Add arguments to geom_point() and reassign it to pl. (Figure out what shape= and size=)
pl <- ggplot(df,aes(x=CPI,y=HDI,color=Region)) + geom_point(size=4,shape=1)
pl
```

```{r}
#Step 4:

#Add geom_smooth(aes(group=1)) to add a trend line

pl + geom_smooth(aes(group=1))
```

```{r}
#Step 5:
#Let us further edit this trend line. Add the following arguments to geom_smooth (outside of aes):

#method = 'lm' formula = y ~ log(x) se = FALSE color = 'red' Assign this to pl2

pl2 <- pl + geom_smooth(aes(group=1),method ='lm',
                        formula = y~log(x),se=FALSE,color='red')
pl2
```
```{r}
#Let us add labels by using geom_text. Add geom_text(aes(label=Country)) to pl2.

pl2 + geom_text(aes(label=Country))
```
```{r}
#Too many labels. Let us display selected lables. Create a lookup list which stores the country names we want to display. and apply the filter in the geom_text() part.

pointsToLabel <- c("Russia", "Venezuela", "Iraq", "Myanmar", "Sudan",
                   "Afghanistan", "Congo", "Greece", "Argentina", "Brazil",
                   "India", "Italy", "China", "South Africa", "Spane",
                   "Botswana", "Cape Verde", "Bhutan", "Rwanda", "France",
                   "United States", "Germany", "Britain", "Barbados", "Norway", "Japan",
                   "New Zealand", "Singapore")

pl3 <- pl2 + geom_text(aes(label = Country), color = "gray20", 
                data = subset(df, Country %in% pointsToLabel),check_overlap = TRUE)

pl3
```
```{r}
#Step 7:

#Add theme_bw() to your plot and save this to pl4

pl4 <- pl3 + theme_bw() 
pl4
```
```{r}
#Step 8:

#Add scale_x_continuous() and set the following arguments:

#name = Same x axis as the Economist Plot limits = Pass a vector of appropriate x limits breaks = 1:10

pl5 <- pl4 + scale_x_continuous(name = "Corruption Perceptions Index, 2011 (10=least corrupt)",
                     limits = c(.9, 10.5),breaks=1:10) 
pl5
```

```{r}
#use scale_y_continuous to do similar operations to the y axis

pl6 <- pl5 + scale_y_continuous(name = "Human Development Index, 2011 (1=Best)",
                     limits = c(0.2, 1.0))
pl6
```
```{r}
#Step 9:

#use ggtitle() to add a string as a title.

pl6 + ggtitle("Corruption and Human development")
```

```{r}
#Step 10:

#Add the economist theme.

library(ggthemes)
```

```{r}
pl6 + theme_economist_white()
```


